version: '3.8'

services:
  # gRPC Service application
  fraud-service:
    build:
      context: ./fraud-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Spring Boot web port
      - "9090:9090"  # gRPC port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - fraud-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Client application
  fraud-client:
    build:
      context: ./fraud-client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Client web port
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GRPC_SERVER_HOST=fraud-service
      - GRPC_SERVER_PORT=9090
    networks:
      - fraud-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    depends_on:
      fraud-service:
        condition: service_healthy

networks:
  fraud-net:
    driver: bridge